def PatternCount():
    genome = "AACTCTATACCTCCTTTTTGTCGAATTTGTGTGATTTATAGAGAAAATCTTATTAACTGAAACTAAAATGGTAGGTTTGGTGGTAGGTTTTGTGTACATTTTGTAGTATCTGATTTTTAATTACATACCGTATATTGTATTAAATTGACGAACAATTGCATGGAATTGAATATATGCAAAACAAACCTACCACCAAACTCTGTATTGACCATTTTAGGACAACTTCAGGGTGGTAGGTTTCTGAAGCTCTCATCAATAGACTATTTTAGTCTTTACAAACAATATTACCGTTCAGATTCAAGATTCTACAACGCTGTTTTAATGGGCGTTGCAGAAAACTTACCACCTAAAATCCAGTATCCAAGCCGATTTCAGAGAAACCTACCACTTACCTACCACTTACCTACCACCCGGGTGGTAAGTTGCAGACATTATTAAAAACCTCATCAGAAGCTTGTTCAAAAATTTCAATACTCGAAACCTACCACCTGCGTCCCCTATTATTTACTACTACTAATAATAGCAGTATAATTGATCTGA"
    Pattern_1 = "ATGATCAAG"
    Pattern_2 = "CTTGATCAT"
    count_1 = 0
    count_2 = 0
    p = len(Pattern_1)
    positions = []
    for i in range(len(genome)):

        if (genome[i:i + p] == Pattern_1):
             count_1 += 1
        if (genome[i:i + p] == Pattern_2):
             count_2 += 1

    return count_1, count_2
count_1, count_2 = PatternCount()
print (count_1, count_2)
print("count is " + str(count_1))
